name: main taski workflow

on:
  push:
    branches:
      - master

jobs:
  checkout-and-tree-print:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Print tree
        run: tree .
